audio.device: BlackHole 2ch
projectM.displayDuration: 60.54899978637695
projectM.enableSplash: false
projectM.presetLocked: false
projectM.presetPath: /Users/delta/doritostash/deltaryz assets/deltamix stream/projectm presets
projectM.shuffleEnabled: true
projectM.transitionDuration: 10
window.height: 448
window.left: 666
window.monitor: 2
window.overridePosition: false
window.top: 212
window.width: 850
